name: Deploy the code
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          # Command to execute on the remote server.
          command: ./deploy.sh
          # Hostname or IP address of the server.
          host: { { secrets.HOST_NAME } }
          # Username for authentication.
          username: { { secrets.USERNAME } }
          # Port number of the server.
          port: 22
          # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          privateKey: { { secrets.PRIVATE_KEY } }
